apiVersion: v2
name: cert-manager-webhook-infoblox
type: application
version: 2.0.0
appVersion: "2.0.0"
description: cert-manager DNS01 webhook solver for Infoblox WAPI
home: https://github.com/tazthemaniac/cert-manager-webhook-infoblox
keywords:
  - cert-manager
  - webhook
  - dns01
  - infoblox
  - wapi
  - acme
sources:
  - https://github.com/tazthemaniac/cert-manager-webhook-infoblox
maintainers:
  - name: tazthemaniac
